import express from'express';import helmet from'helmet';import compression from'compression';import rateLimit from'express-rate-limit';import pg from'pg';import{SignJWT,jwtVerify}from'jose';import{z}from'zod';import path from'node:path';import{fileURLToPath}from'node:url';
const app=express(),port=Number(process.env.PORT||3000),secret=new TextEncoder().encode(process.env.JWT_SECRET||'local-development-secret-change-me');app.use(helmet({contentSecurityPolicy:false}));app.use(compression());app.use(express.json({limit:'1mb'}));app.use('/api',rateLimit({windowMs:60000,limit:180}));
const pool=process.env.DATABASE_URL?new pg.Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false}):null;
const questions=[{id:1,prompt:'What is this called in Arabic?',word:'قَهْوَة',image:'/assets/coffee.png',options:['كِتَاب','قَهْوَة','بَاب'],answer:1},{id:2,prompt:'Choose the Arabic word for “book”.',word:'Book',image:'/assets/book.svg',options:['مِفْتَاح','كُرْسِيّ','كِتَاب'],answer:2},{id:3,prompt:'Which greeting means “Hello”?',word:'Hello',image:'/assets/speech.svg',options:['مَرْحَبًا','شُكْرًا','مَعَ السَّلَامَة'],answer:0},{id:4,prompt:'Choose the Arabic word for “apple”.',word:'Apple',image:'/assets/apple.svg',options:['تُفَّاحَة','مَاء','سَيَّارَة'],answer:0},{id:5,prompt:'What number is this?',word:'٣',image:'/assets/three.svg',options:['وَاحِد','ثَلَاثَة','خَمْسَة'],answer:1}];let memory=[];
async function init(){if(pool)await pool.query('CREATE TABLE IF NOT EXISTS attempts(id BIGSERIAL PRIMARY KEY,name TEXT NOT NULL,language TEXT NOT NULL,score INT NOT NULL,total INT NOT NULL,answers JSONB NOT NULL,created_at TIMESTAMPTZ DEFAULT NOW())')}
const auth=async(req,res,next)=>{try{const h=req.headers.authorization;if(!h?.startsWith('Bearer '))throw 0;await jwtVerify(h.slice(7),secret);next()}catch{res.status(401).json({error:'Unauthorized'})}};
app.get('/api/health',async(_q,r)=>{try{if(pool)await pool.query('SELECT 1');r.json({ok:true,database:!!pool})}catch{r.status(503).json({ok:false})}});app.get('/api/quiz',(_q,r)=>r.json({title:'Level 1 Challenge',questions:questions.map(({answer,...q})=>q)}));
app.post('/api/submit',async(req,res)=>{const p=z.object({name:z.string().trim().min(2).max(60),language:z.string().max(10),answers:z.array(z.number().int()).length(questions.length)}).safeParse(req.body);if(!p.success)return res.status(400).json({error:'Please complete every answer.'});const score=questions.reduce((s,q,i)=>s+(q.answer===p.data.answers[i]?1:0),0),row={id:Date.now(),...p.data,score,total:questions.length,created_at:new Date().toISOString()};if(pool){const q=await pool.query('INSERT INTO attempts(name,language,score,total,answers) VALUES($1,$2,$3,$4,$5) RETURNING id,created_at',[row.name,row.language,score,row.total,JSON.stringify(row.answers)]);Object.assign(row,q.rows[0])}else memory.push(row);res.json({score,total:row.total,percent:Math.round(score/row.total*100)})});
app.post('/api/admin/login',async(req,res)=>{if(req.body?.password!==(process.env.ADMIN_PASSWORD||'admin-demo'))return res.status(401).json({error:'Incorrect password'});res.json({token:await new SignJWT({role:'admin'}).setProtectedHeader({alg:'HS256'}).setExpirationTime('8h').sign(secret)})});
app.get('/api/admin/results',auth,async(_q,res)=>res.json(pool?(await pool.query('SELECT id,name,language,score,total,created_at FROM attempts ORDER BY score DESC,created_at ASC')).rows:[...memory].sort((a,b)=>b.score-a.score)));app.delete('/api/admin/results',auth,async(_q,res)=>{if(pool)await pool.query('TRUNCATE attempts RESTART IDENTITY');else memory=[];res.json({ok:true})});
const root=path.dirname(fileURLToPath(import.meta.url));app.use(express.static(path.join(root,'dist')));app.use((_q,r)=>r.sendFile(path.join(root,'dist','index.html')));init().then(()=>app.listen(port,'0.0.0.0',()=>console.log(`Listening on ${port}`)));
