import express from'express';import helmet from'helmet';import compression from'compression';import rateLimit from'express-rate-limit';import pg from'pg';import{SignJWT,jwtVerify}from'jose';import{z}from'zod';import path from'node:path';import{fileURLToPath}from'node:url';import{randomInt,randomUUID}from'node:crypto';import{questionBank,localizeQuestion,supportedLanguages}from'./question-bank.js';
const app=express(),port=Number(process.env.PORT||3000),secret=new TextEncoder().encode(process.env.JWT_SECRET||'local-development-secret-change-me'),quizSize=15,quizLifetime=30*60*1000;app.use(helmet({contentSecurityPolicy:false}));app.use(compression());app.use(express.json({limit:'1mb'}));app.use('/api',rateLimit({windowMs:60000,limit:180}));
const pool=process.env.DATABASE_URL?new pg.Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false}):null;let memory=[];const memoryQuizzes=new Map();
function shuffle(items){const result=[...items];for(let i=result.length-1;i>0;i--){const j=randomInt(i+1);[result[i],result[j]]=[result[j],result[i]]}return result}
async function init(){if(!pool)return;await pool.query('CREATE TABLE IF NOT EXISTS attempts(id BIGSERIAL PRIMARY KEY,name TEXT NOT NULL,language TEXT NOT NULL,score INT NOT NULL,total INT NOT NULL,answers JSONB NOT NULL,created_at TIMESTAMPTZ DEFAULT NOW())');await pool.query('CREATE TABLE IF NOT EXISTS quiz_sessions(id UUID PRIMARY KEY,language TEXT NOT NULL,question_ids JSONB NOT NULL,answer_keys JSONB NOT NULL,expires_at TIMESTAMPTZ NOT NULL,used_at TIMESTAMPTZ)')}
const auth=async(req,res,next)=>{try{const h=req.headers.authorization;if(!h?.startsWith('Bearer '))throw 0;await jwtVerify(h.slice(7),secret);next()}catch{res.status(401).json({error:'Unauthorized'})}};
app.get('/api/health',async(_q,r)=>{try{if(pool)await pool.query('SELECT 1');r.json({ok:true,database:!!pool,questionBank:questionBank.length})}catch{r.status(503).json({ok:false})}});
app.get('/api/quiz',async(req,res)=>{try{const language=supportedLanguages.includes(req.query.language)?req.query.language:'en',selected=shuffle(questionBank).slice(0,quizSize),prepared=selected.map(item=>{const localized=localizeQuestion(item,language),options=shuffle(localized.options);return{question:{...localized,options},correct:options.indexOf(item.answer)}}),quizId=randomUUID(),expiresAt=new Date(Date.now()+quizLifetime);if(pool){await pool.query('DELETE FROM quiz_sessions WHERE expires_at<NOW() OR used_at<NOW()-INTERVAL \'1 day\'');await pool.query('INSERT INTO quiz_sessions(id,language,question_ids,answer_keys,expires_at) VALUES($1,$2,$3,$4,$5)',[quizId,language,JSON.stringify(selected.map(x=>x.id)),JSON.stringify(prepared.map(x=>x.correct)),expiresAt])}else{for(const[id,q]of memoryQuizzes)if(q.expiresAt<Date.now()||q.used)memoryQuizzes.delete(id);memoryQuizzes.set(quizId,{language,answers:prepared.map(x=>x.correct),expiresAt:expiresAt.getTime(),used:false})}res.json({quizId,language,total:quizSize,bankSize:questionBank.length,questions:prepared.map(x=>x.question)})}catch(error){console.error(error);res.status(500).json({error:'Could not create the quiz.'})}});
const submission=z.object({name:z.string().trim().min(2).max(60),language:z.enum(supportedLanguages),quizId:z.string().uuid(),answers:z.array(z.number().int().min(0).max(2)).length(quizSize)});
app.post('/api/submit',async(req,res)=>{const parsed=submission.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'Please complete every answer.'});const data=parsed.data;if(pool){const client=await pool.connect();try{await client.query('BEGIN');const found=await client.query('SELECT language,answer_keys,expires_at,used_at FROM quiz_sessions WHERE id=$1 FOR UPDATE',[data.quizId]);if(!found.rowCount){await client.query('ROLLBACK');return res.status(404).json({error:'Quiz session not found.'})}const session=found.rows[0];if(session.used_at){await client.query('ROLLBACK');return res.status(409).json({error:'This quiz was already submitted.'})}if(new Date(session.expires_at)<=new Date()){await client.query('ROLLBACK');return res.status(410).json({error:'This quiz has expired.'})}if(session.language!==data.language){await client.query('ROLLBACK');return res.status(400).json({error:'Quiz language does not match.'})}const keys=session.answer_keys,score=keys.reduce((sum,key,index)=>sum+(key===data.answers[index]?1:0),0);await client.query('UPDATE quiz_sessions SET used_at=NOW() WHERE id=$1',[data.quizId]);const saved=await client.query('INSERT INTO attempts(name,language,score,total,answers) VALUES($1,$2,$3,$4,$5) RETURNING id,created_at',[data.name,data.language,score,quizSize,JSON.stringify(data.answers)]);await client.query('COMMIT');return res.json({score,total:quizSize,percent:Math.round(score/quizSize*100),attemptId:saved.rows[0].id})}catch(error){await client.query('ROLLBACK');console.error(error);return res.status(500).json({error:'Could not save the result.'})}finally{client.release()}}
const session=memoryQuizzes.get(data.quizId);if(!session)return res.status(404).json({error:'Quiz session not found.'});if(session.used)return res.status(409).json({error:'This quiz was already submitted.'});if(session.expiresAt<=Date.now())return res.status(410).json({error:'This quiz has expired.'});if(session.language!==data.language)return res.status(400).json({error:'Quiz language does not match.'});session.used=true;const score=session.answers.reduce((sum,key,index)=>sum+(key===data.answers[index]?1:0),0),row={id:Date.now(),...data,score,total:quizSize,created_at:new Date().toISOString()};memory.push(row);res.json({score,total:quizSize,percent:Math.round(score/quizSize*100),attemptId:row.id})});
app.post('/api/admin/login',async(req,res)=>{if(req.body?.password!==(process.env.ADMIN_PASSWORD||'admin-demo'))return res.status(401).json({error:'Incorrect password'});res.json({token:await new SignJWT({role:'admin'}).setProtectedHeader({alg:'HS256'}).setExpirationTime('8h').sign(secret)})});
app.get('/api/admin/results',auth,async(_q,res)=>res.json(pool?(await pool.query('SELECT id,name,language,score,total,created_at FROM attempts ORDER BY score DESC,created_at ASC')).rows:[...memory].sort((a,b)=>b.score-a.score)));app.delete('/api/admin/results',auth,async(_q,res)=>{if(pool)await pool.query('TRUNCATE attempts RESTART IDENTITY');else memory=[];res.json({ok:true})});
const root=path.dirname(fileURLToPath(import.meta.url));app.use(express.static(path.join(root,'dist')));app.use((_q,r)=>r.sendFile(path.join(root,'dist','index.html')));init().then(()=>app.listen(port,'0.0.0.0',()=>console.log(`Listening on ${port}`))).catch(error=>{console.error(error);process.exit(1)});
